// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogrziamwictrjrdaihct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ncnppYW13aWN0cmpyZGFpaGN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczODY0NzgsImV4cCI6MjA2Mjk2MjQ3OH0.UZcUpL_E9KbkNN3imNs-c74EKEa4VMRn-__zi9CfTk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);